/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewRouteImport } from './routes/new'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExpensesIndexRouteImport } from './routes/expenses/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as ExpenseExpenseIdRouteImport } from './routes/expense/$expenseId'
import { Route as AuthLoginRouteImport } from './routes/auth/login'

const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesIndexRoute = ExpensesIndexRouteImport.update({
  id: '/expenses/',
  path: '/expenses/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpenseExpenseIdRoute = ExpenseExpenseIdRouteImport.update({
  id: '/expense/$expenseId',
  path: '/expense/$expenseId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/auth/login': typeof AuthLoginRoute
  '/expense/$expenseId': typeof ExpenseExpenseIdRoute
  '/account/': typeof AccountIndexRoute
  '/expenses/': typeof ExpensesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/auth/login': typeof AuthLoginRoute
  '/expense/$expenseId': typeof ExpenseExpenseIdRoute
  '/account': typeof AccountIndexRoute
  '/expenses': typeof ExpensesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/auth/login': typeof AuthLoginRoute
  '/expense/$expenseId': typeof ExpenseExpenseIdRoute
  '/account/': typeof AccountIndexRoute
  '/expenses/': typeof ExpensesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/new'
    | '/auth/login'
    | '/expense/$expenseId'
    | '/account/'
    | '/expenses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/new'
    | '/auth/login'
    | '/expense/$expenseId'
    | '/account'
    | '/expenses'
  id:
    | '__root__'
    | '/'
    | '/new'
    | '/auth/login'
    | '/expense/$expenseId'
    | '/account/'
    | '/expenses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewRoute: typeof NewRoute
  AuthLoginRoute: typeof AuthLoginRoute
  ExpenseExpenseIdRoute: typeof ExpenseExpenseIdRoute
  AccountIndexRoute: typeof AccountIndexRoute
  ExpensesIndexRoute: typeof ExpensesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/': {
      id: '/expenses/'
      path: '/expenses'
      fullPath: '/expenses/'
      preLoaderRoute: typeof ExpensesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expense/$expenseId': {
      id: '/expense/$expenseId'
      path: '/expense/$expenseId'
      fullPath: '/expense/$expenseId'
      preLoaderRoute: typeof ExpenseExpenseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewRoute: NewRoute,
  AuthLoginRoute: AuthLoginRoute,
  ExpenseExpenseIdRoute: ExpenseExpenseIdRoute,
  AccountIndexRoute: AccountIndexRoute,
  ExpensesIndexRoute: ExpensesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
